POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1OTdkZjRhMWIwNDMyYmZiY2M2YjIzNSIsImlhdCI6MTcwNDQ3MTA3OCwiZXhwIjoxNzA0NDc0Njc4fQ.pTeOmsvKG8WaZB96XVJxnOE_g_thcfVC9pDzSrgObxk

{
    "title": "Test Blog 4",
    "author": "John Doe",
    "url": "test.com",
    "likes": 10,
    "userId": "6597df4a1b0432bfbcc6b235"
}
